### ISSUE TITLE
Timeout Cannot Be Boolean

### ISSUE THREAD

**Issue by buddhhu** [martyzz1/heroku3.py#105]
```Traceback (most recent call last):
  File "/root/TeamUltroid/plugins/devtools.py", line 132, in _
    await aexec(cmd, event)
  File "/root/TeamUltroid/plugins/devtools.py", line 181, in aexec
    return await locals()["__aexec"](event, event.client)
  File "<string>", line 7, in __aexec
  File "/usr/local/lib/python3.9/site-packages/heroku3/api.py", line 526, in get_app_log
    return logger.get(timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/heroku3/models/logsession.py", line 27, in get
    r = requests.get(self.logplex_url, verify=False, stream=True, timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 435, in send
    timeout = TimeoutSauce(connect=timeout, read=timeout)
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 103, in __init__
    self._connect = self._validate_timeout(connect, "connect")
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 137, in _validate_timeout
    raise ValueError(
ValueError: Timeout cannot be a boolean value. It must be an int, float or None.

**Comment by buddhhu** [comment]
> ```
>   File "/root/TeamUltroid/plugins/devtools.py", line 132, in _
>     await aexec(cmd, event)
>   File "/root/TeamUltroid/plugins/devtools.py", line 181, in aexec
>     return await locals()["__aexec"](event, event.client)
>   File "<string>", line 7, in __aexec
>   File "/usr/local/lib/python3.9/site-packages/heroku3/api.py", line 526, in get_app_log
>     return logger.get(timeout=timeout)
>   File "/usr/local/lib/python3.9/site-packages/heroku3/models/logsession.py", line 27, in get
>     r = requests.get(self.logplex_url, verify=False, stream=True, timeout=timeout)
>   File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 76, in get
>     return request('get', url, params=params, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 435, in send
>     timeout = TimeoutSauce(connect=timeout, read=timeout)
>   File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 103, in __init__
>     self._connect = self._validate_timeout(connect, "connect")
>   File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 137, in _validate_timeout
>     raise ValueError(
> ValueError: Timeout cannot be a boolean value. It must be an int, float or None.
> ```

On doing this 👇
```import heroku3

print(heroku3.from_key(api_key).get_app_log(app_name))```
