### ISSUE TITLE
Fails on Python 3.5

### ISSUE THREAD

**Issue by danpalmer** [martyzz1/heroku3.py#13]
```
>>> import heroku3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python3.5/site-packages/heroku3/__init__.py", line 27, in <module>
    from .core import from_key
  File ".../lib/python3.5/site-packages/heroku3/core.py", line 10, in <module>
    from .api import Heroku
  File ".../lib/python3.5/site-packages/heroku3/api.py", line 203
    print "Warning Response was chunked, Loading the next Chunk using the following next-range header returned by Heroku '{0}'. WARNING - This breaks randomly depending on your order_by name. I think it's only guarenteed to work with id's - Looks to be a Heroku problem".format(valrange)
```

**Comment by danpalmer** [comment]
This is a print statement, instead of print function.

**Comment by martyzz1** [comment]
Hi Dan,  I haven't tested this against Python 3 as yet, but I've pushed the following commit to master
#0e98efb

**Comment by danpalmer** [comment]
@martyzz1 I'm really sorry, in my rush to get the Heroku API working on Python 3 I read this as being a Python 3 compatible fork of the Heroku API library. I realise now I was completely wrong. Thanks anyway, much appreciated.

**Comment by martyzz1** [comment]
No worries,  I'm not using this on a daily basis at the moment, but if
there's anything major that stands out, I could take a look to get it
python3 compatible...

I'm looking to build myself a sensible test suite as a first step...

**Comment by yltang52** [comment]
I got the same error message, too, and it's been a year since this issue was reported. When will `heroku3` supports Python 3? Thanks for your efforts.

**Comment by martyzz1** [comment]
Are you using latest pup or latest master?

**Comment by yltang52** [comment]
I just did a `pip3 install heroku3`

**Comment by martyzz1** [comment]
try installing the latest version direct from github. I haven't made a new release to pip in a while - I lost my configs when I changed laptops a while back, so haven't spent the time making the new release to pip... But I think that particular error got fixed..

**Comment by yltang52** [comment]
In my Django project, I changed to `git+git://github.com/martyzz1/heroku3.py` in the `requirements.txt`, but still got the following error message:

    Traceback (most recent call last):
      File "/app/.heroku/python/lib/python3.5/runpy.py", line 184, in _run_module_as_main
        "__main__", mod_spec)
      File "/app/.heroku/python/lib/python3.5/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/app/createStats/stopWorker.py", line 1, in <module>
        import heroku3
      File "/app/.heroku/python/lib/python3.5/site-packages/heroku3/__init__.py", line 27, in <module>
        from .core import from_key
      File "/app/.heroku/python/lib/python3.5/site-packages/heroku3/core.py", line 10, in <module>
        from .api import Heroku
      File "/app/.heroku/python/lib/python3.5/site-packages/heroku3/api.py", line 11, in <module>
        from .helpers import is_collection
      File "/app/.heroku/python/lib/python3.5/site-packages/heroku3/helpers.py", line 12, in <module>
        from dateutil.parser import parse as parse_datetime
      File "/app/.heroku/python/lib/python3.5/site-packages/dateutil/parser.py", line 158
        l.append("%s=%s" % (attr, `value`))
                                  ^
    SyntaxError: invalid syntax

**Comment by yltang52** [comment]
According to [this] [1], I added another line `python-dateutil==2.5.3` to `requirements.txt`. Well, erros kept coming:

    Traceback (most recent call last):
      File "/app/.heroku/python/lib/python3.5/runpy.py", line 184, in _run_module_as_main
        "__main__", mod_spec)
      File "/app/.heroku/python/lib/python3.5/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/app/createStats/stopWorker.py", line 1, in <module>
        import heroku3
      File "/app/.heroku/python/lib/python3.5/site-packages/heroku3/__init__.py", line 27, in <module>
        from .core import from_key
      File "/app/.heroku/python/lib/python3.5/site-packages/heroku3/core.py", line 10, in <module>
        from .api import Heroku
      File "/app/.heroku/python/lib/python3.5/site-packages/heroku3/api.py", line 13, in <module>
        from .models.app import App
      File "/app/.heroku/python/lib/python3.5/site-packages/heroku3/models/app.py", line 2, in <module>
        from ..rendezvous import Rendezvous
      File "/app/.heroku/python/lib/python3.5/site-packages/heroku3/rendezvous.py", line 6, in <module>
        from urlparse import urlparse, uses_netloc
    ImportError: No module named 'urlparse'

[1]: https://github.com/ProgVal/Limnoria/issues/775

**Comment by martyzz1** [comment]
you could try forking this repo and make a python 3 branch. Edit the requirements.txt 
https://github.com/martyzz1/heroku3.py/blob/master/requirements.txt
and update to the python3 compatible libs...  And try that..

I don't use python3 at the moment, so don't have any time to do this. But if you want to poke around for a bit, I'd happily accept a PR.

**Comment by yltang52** [comment]
Porting from Python2 to Python3 is done and a PR is issued. However, I have no idea how to make `git+git://github.com/yltang52/heroku3.py` in `requirements.txt` to install certain versions of `requests` and `python-dateutil`. Currently, I have to add two more lines in the `requirements.txt` after `git+git://github.com/yltang52/heroku3.py` just to prevent from installing Python2 packages of `requests` and `python-dateutil`.:

    git+git://github.com/yltang52/heroku3.py
    requests>=2.11.1
    python-dateutil>=2.6.0

**Comment by martyzz1** [comment]
Think you can update the heroku3/requirements.txt   to the updated
versions... but will then need to test it works ok on 2 as well :)

**Comment by martyzz1** [comment]
https://github.com/martyzz1/heroku3.py/releases/tag/v3.2.0

**Comment by martyzz1** [comment]
Release to pypi too
