### ISSUE TITLE
Exception with Python2.7.15

### ISSUE THREAD

**Issue by nilsabdi** [martyzz1/heroku3.py#82]
```
Traceback (most recent call last):
  File "/venv/lib/python2.7/site-packages/heroku3/__init__.py", line 27, in <module>
    from .core import from_key
  File "/venv/lib/python2.7/site-packages/heroku3/core.py", line 12, in <module>
    from .api import Heroku
  File "/venv/lib/python2.7/site-packages/heroku3/api.py", line 22, in <module>
    from .models.app import App
  File "/venv/lib/python2.7/site-packages/heroku3/models/app.py", line 6, in <module>
    from ..rendezvous import Rendezvous
  File "/venv/lib/python2.7/site-packages/heroku3/rendezvous.py", line 7, in <module>
    from six.moves.urllib.parse import urlparse, uses_netloc
ImportError: cannot import name uses_netloc
```

Running into this issue on Python 2.7.15.
Any suggested course of action?

**Comment by mrmikardo** [comment]
Hi @nilsabdi is this still an issue for you?

**Comment by martyzz1** [comment]
I'm going to close this issue as I've dropped python 2.7 support in the latest versions.
